embedBinaryContent.enabled=true
auth.server.url= https://Identity.mycurecloud.com/AuthPortal/oauth/token
auth.client.id=380e8b43-c7f2-4b1d-bc11-577a8f0417e4
auth.client.secret=283b8738971f4244bff653d1179b306c
auth.grant.type=password
auth.password=ZHGLyrYVd5z
CM12N.username=CM12NFHIR
CM12N.password=ZHGLyrYVd5z
CMDAN.username=CMDANFHIR
CMDAN.password=ZHGLyrYVd5z
CM0FW.username=CM0FWFHIR
CM0FW.password=ZHGLyrYVd5z
CM060.username=CM060FHIR
CM060.password=ZHGLyrYVd5z
DEFAULT.username=CM12NFHIR
DEFAULT.password=ZHGLyrYVd5z