spring.application.name=keycloak-web-app
server.port=8090

spring.security.oauth2.client.registration.keycloak.client-id=test
spring.security.oauth2.client.registration.keycloak.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.keycloak.client-secret=n5yxpKRxIkl7pYFwqV2AIQUzqxsSPdvm
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.keycloak.redirect-uri=http://172.16.103.127:8082/login/oauth2/code/keycloak
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

#spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email,launch/patient,fhirUser,Patient.read,Observation.read,Organisation.read

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://172.16.103.127:8082/realms/testing
spring.security.oauth2.client.provider.keycloak.authorization-uri=http://172.16.103.127:8082/realms/testing/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.token-uri=http://172.16.103.127:8082/realms/testing/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.user-info-uri=http://172.16.103.127:8082/realms/testing/protocol/openid-connect/userinfo
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=http://172.16.103.127:8082/realms/testing/protocol/openid-connect/certs