spring.application.name=keycloak-web-app
server.forward-headers-strategy=framework
server.port=8090

# --- Registration (PKCE/public client) ---
spring.security.oauth2.client.registration.keycloak.client-id=leap_10g
spring.security.oauth2.client.registration.keycloak.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.keycloak.client-secret=6cIu9x9mvcjbX9on5TLcp83ml6Wm5p04
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri=http://cmdlhrltx238:8090/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email

# --- Provider (unchanged) ---
spring.security.oauth2.client.provider.keycloak.issuer-uri=https://identitystaging.curemd.net/realms/leap_staging
spring.security.oauth2.client.provider.keycloak.authorization-uri=https://identitystaging.curemd.net/realms/leap_staging/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.token-uri=https://identitystaging.curemd.net/realms/leap_staging/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.user-info-uri=https://identitystaging.curemd.net/realms/leap_staging/protocol/openid-connect/userinfo
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=https://identitystaging.curemd.net/realms/leap_staging/protocol/openid-connect/certs
