spring.application.name=keycloak-web-app
#server.port=8090

server.port=8443

server.ssl.key-store=file:/C:/Users/yasir.rehman/yasir-workspace/keycloak-projects/keycloak-web-app/src/main/resources/keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=intercom

spring.security.oauth2.client.registration.keycloak.client-id=test
spring.security.oauth2.client.registration.keycloak.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.keycloak.client-secret=zXNsdj4FyFFEf3IfE3LiNc8mJzJbHRDP
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.keycloak.redirect-uri=https://fhirsmartauthsandbox.curemd.net/login/oauth2/code/keycloak
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

#spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email,launch/patient,fhirUser,Patient.read,Observation.read,Organisation.read

spring.security.oauth2.client.provider.keycloak.issuer-uri=https://fhirsmartauthsandbox.curemd.net/realms/FhirSandbox
spring.security.oauth2.client.provider.keycloak.authorization-uri=https://fhirsmartauthsandbox.curemd.net/realms/FhirSandbox/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.token-uri=https://fhirsmartauthsandbox.curemd.net/realms/FhirSandbox/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.user-info-uri=https://fhirsmartauthsandbox.curemd.net/realms/FhirSandbox/protocol/openid-connect/userinfo
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=https://fhirsmartauthsandbox.curemd.net/realms/FhirSandbox/protocol/openid-connect/certs


keycloak.url=https://keycloak.curemd.net/
keycloak.realm=leap
keycloak.admin.realm=leap
keycloak.client-id=test
keycloak.client-secret=464655465sfdsfa
keycloak.username=465
keycloak.password=464-password

