spring.application.name=keycloak-web-app
server.port=8090

spring.security.oauth2.client.registration.keycloak.client-id=test
spring.security.oauth2.client.registration.keycloak.client-secret=CUbg3v9Yo5Ilo78KP05LECg3muz58oow
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.keycloak.redirect-uri=http://172.16.102.238:8082/login/oauth2/code/keycloak
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email

spring.security.oauth2.client.provider.keycloak.issuer-uri=https://3.229.179.146:8441/realms/leap_staging
spring.security.oauth2.client.provider.keycloak.authorization-uri=https://3.229.179.146:8441/realms/leap_staging/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.token-uri=https://3.229.179.146:8441/realms/leap_staging/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.user-info-uri=https://3.229.179.146:8441/realms/leap_staging/protocol/openid-connect/userinfo
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=https://3.229.179.146:8441/realms/leap_staging/protocol/openid-connect/certs
